// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ApIvjDHji2Qv01oDmEddVIXkSt7pPNI',
    appId: '1:171602015562:web:64a3f890ff0cc80bba7db3',
    messagingSenderId: '171602015562',
    projectId: 'watchly-movie',
    authDomain: 'watchly-movie.firebaseapp.com',
    storageBucket: 'watchly-movie.firebasestorage.app',
    measurementId: 'G-N35MQKTV0M',
    databaseURL: 'https://watchly-movie-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9p_76Teq6EhOrjx1qDbKmEbr8HM2XK3I',
    appId: '1:171602015562:android:0b44228ee1b3d355ba7db3',
    messagingSenderId: '171602015562',
    projectId: 'watchly-movie',
    storageBucket: 'watchly-movie.firebasestorage.app',
    databaseURL: 'https://watchly-movie-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
